# numpy
## pandas

> 라이브러리 예제

    - numpy
    -pandas

In [9]:
#numpy 사용하기
import numpy as np
1
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [26]:
%time for _ in range(10): my_arr2=my_arr*2

IndentationError: unexpected indent (213399222.py, line 2)

In [20]:
%time for _ in range(10): my_list2=[x*2 for x in my_list]

Wall time: 565 ms


In [31]:
data1=np.random.randn(6)
data1

array([-0.36636422, -0.81746592,  0.45536181, -0.30074584,  0.33255819,
       -0.4900883 ])

In [29]:
data=np.random.rand(2,3)
data

array([[0.69547123, 0.23776661, 0.99283964],
       [0.03610075, 0.38229449, 0.88582074]])

In [32]:
data*10

array([[6.95471232, 2.37766608, 9.92839644],
       [0.3610075 , 3.82294488, 8.85820735]])

In [33]:
data

array([[0.69547123, 0.23776661, 0.99283964],
       [0.03610075, 0.38229449, 0.88582074]])

In [34]:
data+data

array([[1.39094246, 0.47553322, 1.98567929],
       [0.0722015 , 0.76458898, 1.77164147]])

In [35]:
data.shape

(2, 3)

In [36]:
data.dtype

dtype('float64')

In [37]:
data1=[2, 5.5, 3, 9, 0]
arr1=np.array(data1)

In [38]:
arr1

array([2. , 5.5, 3. , 9. , 0. ])

In [39]:
arr1.dtype


dtype('float64')

In [49]:
arr2=np.array(arr1, int)
arr2.dtype

dtype('int32')

In [50]:
len(arr2)

5

In [71]:
data3=[[[1]],[[2,3],[4,5,6]]]
data3[1][0][1]=9
data3

[[[1]], [[2, 9], [4, 5, 6]]]

In [65]:
data2=[[1,2,3,4], [5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
arr2.ndim

2

In [76]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
a=np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [87]:
a.dtype

dtype('float64')

In [88]:
np.ones(10, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [89]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
np.empty(10, dtype=np.int8)

array([ 32,   2, -64, -96,  96,   2,   0,   0, 112,  51], dtype=int8)

In [103]:
text_matrix=np.arange(30).reshape(5,6)
text_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [109]:
np.ones_like(text_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [110]:
list_a=list(range(10))
list_a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [113]:
arr1=np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [114]:
arr2=np.array([1,2,3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [124]:
arr2.astype(np.float64)

array([1., 2., 3.])

In [122]:
arr=np.array([1.2, 7.2, -2.4, 10.5])
arr

array([ 1.2,  7.2, -2.4, 10.5])

In [123]:
arr.astype(np.int32)

array([ 1,  7, -2, 10])

In [129]:
int_arr=np.arange(10)
float_arr=np.array([1.2,3.5, 0.9], dtype=np.float64)
int_arr.astype(float_arr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [130]:
data=[0,1,2,3,4,5,6,7,8,9]
answer=[]
for i in data:
    answer.append(2*i)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [132]:
x=np.array(data)
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [134]:
data*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [148]:
arr=np.array([[1,2,3],[4,5,6]], dtype=np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [157]:
arr**3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [165]:
arr2=np.array([[0, 4, 9], [7, 2, 12]], dtype=np.float64)
arr2

array([[ 0.,  4.,  9.],
       [ 7.,  2., 12.]])

In [168]:
arr2>arr

array([[False,  True,  True],
       [ True, False,  True]])

In [169]:
a=np.array([1,2,3])
b=np.array([10,20,30])
a==2

array([False,  True, False])

In [171]:
(a==2) & (b>10)

array([False, False, False])

In [174]:
np.all(a==b)

True

> 연습문제

In [181]:
np.array([[10,20,30], [40,50,60]])

array([[10, 20, 30],
       [40, 50, 60]])

In [185]:
np.arange(10, 61, 10).reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [188]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [202]:
arr_slice=arr[5:8]
arr_slice

array([   12, 12345,    12])

In [199]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [195]:
arr_slice

array([   12, 12345,    12])

In [203]:
arr_slice[:]=64
arr_slice

array([64, 64, 64])

In [204]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [207]:
copy_arr=arr[5:8].copy()
copy_arr[:]=10
copy_arr

array([10, 10, 10])

In [208]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [210]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [211]:
arr2d[0,2]

3

In [222]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [215]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [217]:
arr3d.shape

(2, 2, 3)

In [223]:
old_value=arr3d[0].copy()
arr3d[0]=41
arr3d

array([[[41, 41, 41],
        [41, 41, 41]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [225]:
arr3d[0]=old_value
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [228]:
arr3d[1,0]

array([7, 8, 9])

In [229]:
x=arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [230]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [238]:
arr2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [244]:
arr3d[:,:,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [245]:
m=np.array([[0,1,2,3,4], 
            [5,6,7,8,9], 
            [10,11,12,13,14]])
m[1][2]

7

In [246]:
m[2][4]

14

In [247]:
m[1,1:3]

array([6, 7])

In [248]:
m[1:,2]

array([ 7, 12])

In [249]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [255]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
idx=np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([0, 2, 4, 6, 8])

In [257]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [261]:
names=np.array(['bob', 'kob', 'will', 'bob', 'will', 'joe', 'joe'])
data=np.random.randn(7,4)
names

array(['bob', 'kob', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [262]:
data

array([[-0.37532407,  0.82513152, -0.85128175,  1.5156502 ],
       [-0.8934836 , -0.42617815,  0.44026724,  0.20223825],
       [ 1.10195188, -1.89738106,  0.65423179,  1.91105458],
       [-0.02096215,  2.22625203, -0.5646779 , -1.77060809],
       [ 0.07499613,  0.82225876, -0.29390874, -2.6777531 ],
       [-0.4253145 , -0.34581327,  0.9697208 ,  0.95628367],
       [-1.77759421, -0.00426519,  0.3802224 , -0.76925015]])

In [264]:
names=='bob'

array([ True, False, False,  True, False, False, False])

In [266]:
data[names=='bob']

array([[-0.37532407,  0.82513152, -0.85128175,  1.5156502 ],
       [-0.02096215,  2.22625203, -0.5646779 , -1.77060809]])

In [267]:
data[names=='bob', 2:]

array([[-0.85128175,  1.5156502 ],
       [-0.5646779 , -1.77060809]])

In [268]:
names!='bob'

array([False,  True,  True, False,  True,  True,  True])

In [271]:
data[~(names=='bob')]

array([[-0.8934836 , -0.42617815,  0.44026724,  0.20223825],
       [ 1.10195188, -1.89738106,  0.65423179,  1.91105458],
       [ 0.07499613,  0.82225876, -0.29390874, -2.6777531 ],
       [-0.4253145 , -0.34581327,  0.9697208 ,  0.95628367],
       [-1.77759421, -0.00426519,  0.3802224 , -0.76925015]])

In [273]:
mask=(names=='bob')|(names=='will')
data[mask]

array([[-0.37532407,  0.82513152, -0.85128175,  1.5156502 ],
       [ 1.10195188, -1.89738106,  0.65423179,  1.91105458],
       [-0.02096215,  2.22625203, -0.5646779 , -1.77060809],
       [ 0.07499613,  0.82225876, -0.29390874, -2.6777531 ]])

In [274]:
data<0

array([[ True, False,  True, False],
       [ True,  True, False, False],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False,  True]])

In [282]:
x=np.arange(1,21)
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [277]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [281]:
x[(x%3==0)&(x%4==1)]

array([9])

1. numpy는 기존의 파이썬 내장함수보다 메모리 낭비를 최소화하면서 수학적 계산을 보다 쉽게 해주는 파이썬 라이브러리이다.

2.

In [284]:
np.array([0,1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [285]:
np.arange(0,6)

array([1, 2, 3, 4, 5])

3. list는 한번에 여러 타입을 데이터로 삼을 수 있지만, 배열은 한 가지의 타입밖에 데이터로 삼지 못한다.

4.

In [286]:
x=np.arange(1,21)
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [287]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [288]:
x[(x%3==0)&(x%4==1)]

array([9])